// vecgen — Go-side interop fixture generator / verifier (canonical copy; staged into the
// RANGER_C3 module by scripts/interop.sh, e.g. /tmp/interop-mod/cmd/vecgen/main.go).
//
// Modes:
//
//	gen             — crypto fixtures for the C++ test suite
//	check <file>    — verify C++ crypto artifacts via production Go code paths
//	protocol-gen    — protocol JSON fixtures (marshaled by the Go structs)
//	protocol-check <file> — verify C++ protocol artifacts via Go unmarshal
package main

import (
	"bytes"
	"crypto/ed25519"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"golang.org/x/crypto/chacha20poly1305"

	rrcrypto "git.churchofmalware.org/ek0mssavi0r/Ranger-C3/internal/crypto"
	rrdns "git.churchofmalware.org/ek0mssavi0r/Ranger-C3/internal/dns"
	rrprotocol "git.churchofmalware.org/ek0mssavi0r/Ranger-C3/internal/protocol"
)

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "FAIL: "+format+"\n", args...)
	os.Exit(1)
}

// ---------------------------------------------------------------- crypto ----

func gen() {
	var b strings.Builder

	key := make([]byte, 32)
	for i := range key {
		key[i] = byte(i)
	}
	nonce := make([]byte, 24)
	for i := range nonce {
		nonce[i] = byte(i)
	}
	pt := []byte("ranger c3 interop vector")
	aead, err := chacha20poly1305.NewX(key)
	if err != nil {
		fail("NewX: %v", err)
	}
	blob := aead.Seal(append([]byte{}, nonce...), nonce, pt, nil)
	if out, err := rrcrypto.DecryptWithAEAD(key, blob); err != nil || string(out) != string(pt) {
		fail("production DecryptWithAEAD rejected our own blob")
	}

	seed := make([]byte, 32)
	for i := range seed {
		seed[i] = byte(i + 1)
	}
	priv := ed25519.NewKeyFromSeed(seed)
	pub := priv.Public().(ed25519.PublicKey)
	data := []byte("mesh heartbeat interop")
	ts := int64(1758302400)
	nonceB := make([]byte, 16)
	for i := range nonceB {
		nonceB[i] = byte(0xa0 + i)
	}
	nonceStr := base64.RawStdEncoding.EncodeToString(nonceB)
	msg := append(append([]byte{}, data...), []byte(fmt.Sprintf("%d%s", ts, nonceStr))...)
	sig := ed25519.Sign(priv, msg)

	dsKey := rrcrypto.DeriveSessionKey([]byte("shared-secret"), []byte("dns-tunnel"))
	sh := sha256.Sum256([]byte("solidsnake-native"))

	pemBytes, err := rrcrypto.MarshalPublicKey(pub)
	if err != nil {
		fail("MarshalPublicKey: %v", err)
	}

	fmt.Fprintf(&b, "# Ranger C3 interop fixtures — generated by interop/vecgen.go (do not edit)\n")
	fmt.Fprintf(&b, "aead_key_hex=%s\n", hex.EncodeToString(key))
	fmt.Fprintf(&b, "aead_nonce_hex=%s\n", hex.EncodeToString(nonce))
	fmt.Fprintf(&b, "aead_pt_hex=%s\n", hex.EncodeToString(pt))
	fmt.Fprintf(&b, "aead_blob_hex=%s\n", hex.EncodeToString(blob))
	fmt.Fprintf(&b, "sign_seed_hex=%s\n", hex.EncodeToString(seed))
	fmt.Fprintf(&b, "sign_pub_hex=%s\n", hex.EncodeToString(pub))
	fmt.Fprintf(&b, "sign_data_hex=%s\n", hex.EncodeToString(data))
	fmt.Fprintf(&b, "sign_ts=%d\n", ts)
	fmt.Fprintf(&b, "sign_nonce_b64=%s\n", nonceStr)
	fmt.Fprintf(&b, "sign_sig_hex=%s\n", hex.EncodeToString(sig))
	fmt.Fprintf(&b, "ds_secret_hex=%s\n", hex.EncodeToString([]byte("shared-secret")))
	fmt.Fprintf(&b, "ds_salt_hex=%s\n", hex.EncodeToString([]byte("dns-tunnel")))
	fmt.Fprintf(&b, "ds_key_hex=%s\n", hex.EncodeToString(dsKey))
	fmt.Fprintf(&b, "sha_in_hex=%s\n", hex.EncodeToString([]byte("solidsnake-native")))
	fmt.Fprintf(&b, "sha_out_hex=%s\n", hex.EncodeToString(sh[:]))
	fmt.Fprintf(&b, "pem_b64=%s\n", base64.StdEncoding.EncodeToString(pemBytes))
	fmt.Print(b.String())
}

func check(path string) {
	raw, err := os.ReadFile(path)
	if err != nil {
		fail("read %s: %v", path, err)
	}
	kv := map[string]string{}
	for _, line := range strings.Split(string(raw), "\n") {
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if p := strings.Index(line, "="); p >= 0 {
			kv[line[:p]] = line[p+1:]
		}
	}
	getHex := func(k string) []byte {
		v, err := hex.DecodeString(kv[k])
		if err != nil {
			fail("field %s: %v", k, err)
		}
		return v
	}

	pt, err := rrcrypto.DecryptWithAEAD(getHex("cpp_aead_key_hex"), getHex("cpp_aead_blob_hex"))
	if err != nil {
		fail("Go DecryptWithAEAD on C++ blob: %v", err)
	}
	if hex.EncodeToString(pt) != kv["cpp_aead_pt_hex"] {
		fail("C++ AEAD plaintext mismatch after Go decrypt")
	}
	fmt.Println("OK: Go decrypted C++ AEAD blob (production DecryptWithAEAD)")

	pub := ed25519.PublicKey(getHex("cpp_sign_pub_hex"))
	data := getHex("cpp_sign_data_hex")
	sig := getHex("cpp_sign_sig_hex")
	var ts int64
	if _, err := fmt.Sscanf(kv["cpp_sign_ts"], "%d", &ts); err != nil {
		fail("cpp_sign_ts parse: %v", err)
	}
	if err := rrcrypto.Verify(pub, data, sig, kv["cpp_sign_nonce_b64"], ts, map[string]bool{}); err != nil {
		fail("Go Verify on C++ signature: %v", err)
	}
	fmt.Println("OK: Go verified C++ Ed25519 signature (production Verify)")
}

// -------------------------------------------------------------- protocol ----

func protocolGen() {
	bundle := map[string]any{
		"beacon": rrprotocol.BeaconPayload{
			ID:        "imp-01",
			Type:      rrprotocol.ImplantLinux,
			Target:    "go-target",
			Timestamp: 1758302400,
			Jitter:    0.35,
			Hostname:  "go-host",
		},
		"task": rrprotocol.Task{
			ID:        "t-1001",
			Type:      "exec",
			Payload:   map[string]any{"cmd": "id"},
			Timestamp: 1758302400,
			TTL:       60,
		},
		"task_result": rrprotocol.TaskResult{
			TaskID:    "t-1001",
			Success:   false,
			Error:     "boom",
			Timestamp: 1758302400,
		},
	}
	out, err := json.MarshalIndent(bundle, "", "  ")
	if err != nil {
		fail("marshal: %v", err)
	}
	fmt.Println(string(out))
}

func protocolCheck(path string) {
	raw, err := os.ReadFile(path)
	if err != nil {
		fail("read %s: %v", path, err)
	}
	var b struct {
		Beacon     rrprotocol.BeaconPayload `json:"beacon"`
		Task       rrprotocol.Task          `json:"task"`
		TaskResult rrprotocol.TaskResult    `json:"task_result"`
	}
	if err := json.Unmarshal(raw, &b); err != nil {
		fail("unmarshal C++ artifacts: %v", err)
	}

	if b.Beacon.ID != "imp-cpp-7" || b.Beacon.Type != rrprotocol.ImplantWindows ||
		b.Beacon.Target != "cpp-target" {
		fail("beacon id/type/target mismatch: %+v", b.Beacon)
	}
	if b.Beacon.Timestamp != 1758302500 || b.Beacon.Jitter != 0.5 {
		fail("beacon ts/jitter mismatch: %+v", b.Beacon)
	}
	if b.Beacon.Hostname != "cpp-host" || b.Beacon.Arch != "amd64" || b.Beacon.PeerAddr != "10.0.0.7" {
		fail("beacon hostname/arch/peer_addr mismatch: %+v", b.Beacon)
	}
	fmt.Println("OK: Go parsed C++ beacon (all fields exact, incl. omitempty-populated)")

	if b.Task.ID != "t-2002" || b.Task.Type != "shell" || b.Task.TTL != 30 {
		fail("task id/type/ttl mismatch: %+v", b.Task)
	}
	if len(b.Task.Payload) != 2 || b.Task.Payload["cmd"] != "whoami" || b.Task.Payload["arg"] != "-a" {
		fail("task payload mismatch: %+v", b.Task.Payload)
	}
	fmt.Println("OK: Go parsed C++ task (payload map exact)")

	if b.TaskResult.TaskID != "t-2002" || !b.TaskResult.Success ||
		b.TaskResult.Output != "uid=0(root)" || b.TaskResult.Error != "" {
		fail("task_result mismatch: %+v", b.TaskResult)
	}
	fmt.Println("OK: Go parsed C++ task_result (success/output exact, error omitted)")
}

// dnsCheck verifies C++-produced DNS exfil queries through the real tunnel parser:
// ParseFragment -> ReceiveFragment -> Reconstruct -> AEAD decrypt.
func dnsCheck(path string) {
	raw, err := os.ReadFile(path)
	if err != nil {
		fail("read %s: %v", path, err)
	}
	var sessionKeyHex, domain, payloadHex string
	var queries []string
	for _, line := range strings.Split(string(raw), "\n") {
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if p := strings.Index(line, "="); p >= 0 {
			switch line[:p] {
			case "session_key_hex":
				sessionKeyHex = line[p+1:]
			case "domain":
				domain = line[p+1:]
			case "payload_hex":
				payloadHex = line[p+1:]
			default:
				fail("unknown header field: %s", line[:p])
			}
			continue
		}
		queries = append(queries, line)
	}
	if sessionKeyHex == "" || domain == "" || payloadHex == "" || len(queries) == 0 {
		fail("missing header fields or queries")
	}
	sk, err := hex.DecodeString(sessionKeyHex)
	if err != nil || len(sk) != 32 {
		fail("bad session_key_hex")
	}
	wantPayload, err := hex.DecodeString(payloadHex)
	if err != nil {
		fail("bad payload_hex")
	}

	key := rrcrypto.DeriveSessionKey(sk, []byte("dns-tunnel"))
	t := rrdns.New(domain, key)

	session := ""
	complete := false
	for _, q := range queries {
		f := t.ParseFragment(q)
		if f == nil {
			fail("ParseFragment rejected: %s", q)
		}
		if session == "" {
			session = f.SessionID
		} else if f.SessionID != session {
			fail("session id changed mid-transfer")
		}
		if t.ReceiveFragment(f) {
			complete = true
		}
	}
	if !complete {
		fail("transfer never marked complete (last-chunk heuristic)")
	}
	got, err := t.Reconstruct(session)
	if err != nil {
		fail("reconstruct: %v", err)
	}
	if !bytes.Equal(got, wantPayload) {
		fail("payload mismatch after reassembly: %q", got)
	}
	fmt.Println("OK: Go tunnel parser reassembled C++ DNS exfil payload (ParseFragment/ReceiveFragment/Reconstruct/decrypt)")
}

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintln(os.Stderr, "usage: vecgen gen|protocol-gen | vecgen check|protocol-check <file>")
		os.Exit(2)
	}
	switch os.Args[1] {
	case "gen":
		gen()
	case "check":
		if len(os.Args) < 3 {
			fmt.Fprintln(os.Stderr, "usage: vecgen check <artifacts.txt>")
			os.Exit(2)
		}
		check(os.Args[2])
	case "protocol-gen":
		protocolGen()
	case "protocol-check":
		if len(os.Args) < 3 {
			fmt.Fprintln(os.Stderr, "usage: vecgen protocol-check <artifacts.json>")
			os.Exit(2)
		}
		protocolCheck(os.Args[2])
	case "dns-check":
		if len(os.Args) < 3 {
			fmt.Fprintln(os.Stderr, "usage: vecgen dns-check <queries.txt>")
			os.Exit(2)
		}
		dnsCheck(os.Args[2])
	default:
		fmt.Fprintln(os.Stderr, "unknown mode:", os.Args[1])
		os.Exit(2)
	}
}
